name: "default"
type: "postgres"
host: "Your IP"
port: 5432
username: "postgres"
password: "PASSWORD"
database: "DATABASE"
schema: "SCHEMA"
synchronize: true
logging: false
entities: 
    - "build/entity/**/*.js"
migrations: 
    - "build/migrations/**/*.js"
subscribers: 
    - "build/subscriber/**/*.js"
cli:
    entitiesDir: "build/entity"
    migrationsDir: "build/migrations"
    subscribersDir: "build/subscriber"
